@hostAddress = https://app-mobimart-dev-southeastasia-01.azurewebsites.net


###
POST {{hostAddress}}/users/
Content-Type: application/json

{
    "firstName": "Jake Zyrus",
    "lastName": "Pempengco",
    "email": "jake-zy@gmail.com",
    "password": "39b239b238ds@7n56",
    "birthDate": "2000-05-16",
    "age": 25,
    "phoneNumber": "09053687822",
    "employeeType": "employee"
}


###
GET {{hostAddress}}/users


###
POST {{hostAddress}}/businesses/
Content-Type: application/json

{
    "name": "My Cool Sari-sari Store",
    "address": "456 My House Down the Street",
    "code": "I2JE4"
}


###
DELETE http://localhost:5198/users/2


###
GET {{hostAddress}}/businesses/1



###
POST {{hostAddress}}/inventories
Content-Type: application/json

{
    "businessId": 0,
    "deliveryId": 0,
    "descriptionId": 0,
    "totalAmount": 1,
    "itemName": "Mobi Chips",
    "retailPrice": "6.50",
    "itemType": "supply"
}

###
DELETE http://localhost:5198/descriptions/1



###
POST http://localhost:5198/descriptions
Content-Type: application/json

{
    "itemId": 1,
    "text": "It features crispy corn puffs coated in a sweet chocolate layer, creating a satisfying and indulgent treat. The snack is described as having a light, airy texture and a mild chocolate flavor."
}


###
POST http://localhost:5198/suppliers/
Content-Type: application/json

{
    "businessId": 2,
    "type": "Whole Sale",
    "name": "Jack n' Jill Mdse",
    "email": "Jack.n.Jill@gmail.com",
    "socialsLink": "https://facebook.com/jack-n-jill-mdse",
    "socialsDescription": "facebook page"
}

###
POST http://localhost:5198/suppliers/contacts
Content-Type: application/json

{
    "supplierId": 3,
    "name": "John Mark Sadaya",
    "email": "jmsadaya@gmail.com"
}


###
DELETE http://localhost:5198/suppliers/3

###
GET http://localhost:5198/suppliers/5


### TEST or debug the wholesale inventory endpoint
POST http://localhost:5198/wholesale-inventories
Content-Type: application/json

{
    "supplierId": 5,
    "itemName": "Moby",
    "deliveryAmount": 20,
    "dateDelivered": "2025-06-21",
    "expirationDate": "2027-12-12",
    "batchWorth": 130,
    "itemType": "Junk Food"
}


###
GET {{hostAddress}}

###
GET http://localhost:5198/wholesale-inventories/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiZnh5cnVzMjZAZ21haWwuY29tIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZWlkZW50aWZpZXIiOiIzIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiIiwiZXhwIjoxNzU1NzQ5NzU4LCJpc3MiOiJNb2JpTWFydCIsImF1ZCI6IkF1ZGllbmNlS28ifQ.DtPDGODzdBjoKi-PrskG8UdRdpx9jPk3iN3EpIOTqU0



### authentication
POST {{hostAddress}}/auth/login/

Content-Type: application/json
{
    "email": "fxyrus@gmail.com",
    "password": "jake1234"
} 


### 
DELETE http://localhost:5198/users/17